name: Release

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Checkout"
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: "PNPM"
        with:
          run_install: false

      - uses: actions/setup-node@v4
        name: "NodeJS"
        with:
          node-version: 20
          cache: "pnpm"

      - uses: actions/cache@v4
        name: "Nx"
        with:
          path: .nx
          key: nx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-

      - run: pnpm install --frozen-lockfile --strict-peer-dependencies
        name: Install

      - run: pnpm exec lerna run build
        name: Build

      - run: pnpm exec lerna run release
        name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
