name: Release

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/actions-setup@v4
        with:
          version: 10.6.0
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-

      - run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - run: pnpm exec lerna build
