name: Release

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Checkout"
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: "PNPM"
        with:
          run_install: false

      - uses: actions/setup-node@v4
        name: "NodeJS"
        with:
          node-version: 20
          cache: "pnpm"

      - name: Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - run: pnpm install --frozen-lockfile
        name: Install dependencies

      - run: pnpm run release
        name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NODE_AUTH_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ github.token }}
